from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class Ui_Login(object):
    def setupUi(self, Login):
        if not Login.objectName():
            Login.setObjectName(u"Login")
        Login.resize(800, 400)
        Login.setMinimumSize(QSize(800, 400))
        Login.setMaximumSize(QSize(800, 400))
        Login.setStyleSheet(u"")
        self.btnEntrar = QPushButton(Login)
        self.btnEntrar.setObjectName(u"btnEntrar")
        self.btnEntrar.setGeometry(QRect(510, 240, 101, 31))
        font = QFont()
        font.setFamily(u"Times New Roman")
        self.btnEntrar.setFont(font)
        self.btnEntrar.setStyleSheet(u"background-color:#FDFDFD")
        self.btnApagar = QPushButton(Login)
        self.btnApagar.setObjectName(u"btnApagar")
        self.btnApagar.setGeometry(QRect(630, 240, 101, 31))
        self.btnApagar.setFont(font)
        self.btnApagar.setStyleSheet(u"background-color: #FDFDFD")
        self.imName = QLineEdit(Login)
        self.imName.setObjectName(u"imName")
        self.imName.setGeometry(QRect(510, 120, 221, 31))
        font1 = QFont()
        font1.setFamily(u"Times New Roman")
        font1.setPointSize(11)
        self.imName.setFont(font1)
        self.label = QLabel(Login)
        self.label.setObjectName(u"label")
        self.label.setEnabled(True)
        self.label.setGeometry(QRect(0, 0, 800, 400))
        self.label.setMinimumSize(QSize(800, 400))
        self.label.setMaximumSize(QSize(800, 400))
        self.label.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(u"background-color:#FFFFFF")
        self.ImPassword = QLineEdit(Login)
        self.ImPassword.setObjectName(u"ImPassword")
        self.ImPassword.setGeometry(QRect(510, 190, 221, 31))
        self.ImPassword.setFont(font1)
        self.ImPassword.setEchoMode(QLineEdit.Password)
        self.label_6 = QLabel(Login)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(580, 50, 81, 41))
        self.label_6.setFont(font)
        self.btnCadasto = QPushButton(Login)
        self.btnCadasto.setObjectName(u"btnCadasto")
        self.btnCadasto.setGeometry(QRect(560, 300, 121, 31))
        self.btnCadasto.setFont(font)
        self.btnCadasto.setStyleSheet(u"background-color: #FDFDFD")
        self.label_4 = QLabel(Login)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(480, 30, 281, 321))
        self.label_4.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet(u"background-color: #F0FFFF")
        self.label_5 = QLabel(Login)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(110, 160, 271, 191))
        self.label_5.setStyleSheet(u"background-color: #FFFFFF")
        self.label_7 = QLabel(Login)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(510, 100, 51, 16))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(Login)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(510, 170, 51, 16))
        self.label_8.setFont(font1)
        self.label_9 = QLabel(Login)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 50, 311, 101))
        font2 = QFont()
        font2.setFamily(u"Times New Roman")
        self.label_9.setFont(font2)
        self.label.raise_()
        self.label_4.raise_()
        self.imName.raise_()
        self.ImPassword.raise_()
        self.btnCadasto.raise_()
        self.btnEntrar.raise_()
        self.btnApagar.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()

        self.retranslateUi(Login)

        QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        Login.setWindowTitle(QCoreApplication.translate("Login", u"Tela de Login", None))
        self.btnEntrar.setText(QCoreApplication.translate("Login", u"Entrar", None))
        self.btnApagar.setText(QCoreApplication.translate("Login", u"Apagar", None))
        self.imName.setInputMask("")
        self.imName.setPlaceholderText(QCoreApplication.translate("Login", u"Digite o seu Usu\u00e1rio", None))
        self.label.setText(QCoreApplication.translate("Login", u"<html><head/><body><p><br/></p></body></html>", None))
        self.ImPassword.setInputMask("")
        self.ImPassword.setPlaceholderText(QCoreApplication.translate("Login", u"Digite a senha", None))
        self.label_6.setText(QCoreApplication.translate("Login", u"<html><head/><body><p align=\"center\"><span style=\"font-size:14pt; font-weight:600;\">LOGIN</span></p></body></html>", None))
        self.btnCadasto.setText(QCoreApplication.translate("Login", u"Cadastro", None))
        self.label_4.setText(QCoreApplication.translate("Login", u"<html><head/><body><p><br/></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("Login", u"<html><head/><body><p><img src=\"./Imagens/download.png\"/></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("Login", u"<html><head/><body><p>Usu\u00e1rio</p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("Login", u"<html><head/><body><p>Senha</p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("Login", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Entre em um mundo divertido e</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">eficaz de aprendizado de escrita, de</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">forma gratuita!</span></p></body></html>", None))