from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class Ui_cadastro(object):
    def setupUi(self, cadastro):
        if cadastro.objectName():
            cadastro.setObjectName(u"cadastro")
        cadastro.setFixedSize(400, 300)
        self.titulo_cadastro = QLabel(cadastro)
        self.titulo_cadastro.setObjectName(u"titulo_cadastro")
        self.titulo_cadastro.setGeometry(QRect(170, 20, 91, 39))
        self.titulo_usuario = QLabel(cadastro)
        self.titulo_usuario.setObjectName(u"titulo_usuario")
        self.titulo_usuario.setGeometry(QRect(50, 70, 51, 16))
        self.titulo_senha = QLabel(cadastro)
        self.titulo_senha.setObjectName(u"titulo_senha")
        self.titulo_senha.setGeometry(QRect(50, 110, 51, 20))
        self.titulo_confirmar_senha = QLabel(cadastro)
        self.titulo_confirmar_senha.setObjectName(u"titulo_confirmar_senha")
        self.titulo_confirmar_senha.setGeometry(QRect(50, 150, 51, 16))
        self.imName = QLineEdit(cadastro)
        self.imName.setObjectName(u"imName")
        self.imName.setGeometry(QRect(140, 70, 200, 20))
        self.imPass = QLineEdit(cadastro)
        self.imPass.setObjectName(u"imPass")
        self.imPass.setGeometry(QRect(140, 110, 200, 20))
        self.imPassC = QLineEdit(cadastro)
        self.imPassC.setObjectName(u"imPassC")
        self.imPassC.setGeometry(QRect(140, 150, 200, 20))
        self.btnConfirma = QPushButton(cadastro)
        self.btnConfirma.setObjectName(u"btnConfirma")
        self.btnConfirma.setGeometry(QRect(50, 200, 130, 23))
        self.btnLimpar = QPushButton(cadastro)
        self.btnLimpar.setObjectName(u"btnLimpar")
        self.btnLimpar.setGeometry(QRect(210, 200, 130, 23))
        self.label_5 = QLabel(cadastro)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 0, 400, 300))
        self.label_5.setStyleSheet(u"background-color: rgb(173, 216, 230);")
        self.label_5.raise_()
        self.titulo_cadastro.raise_()
        self.titulo_usuario.raise_()
        self.titulo_senha.raise_()
        self.titulo_confirmar_senha.raise_()
        self.imName.raise_()
        self.imPass.raise_()
        self.imPassC.raise_()
        self.btnConfirma.raise_()
        self.btnLimpar.raise_()

        self.retranslateUi(cadastro)

        QMetaObject.connectSlotsByName(cadastro)

    def retranslateUi(self, cadastro):
        cadastro.setWindowTitle(QCoreApplication.translate("cadastro", u"Dialog", None))
        self.titulo_cadastro.setText(QCoreApplication.translate("cadastro", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Cadastro</span></p></body></html>", None))
        self.titulo_usuario.setText(QCoreApplication.translate("cadastro", u"<html><head/><body><p>Usuario</p></body></html>", None))
        self.titulo_senha.setText(QCoreApplication.translate("cadastro", u"<html><head/><body><p>Senha</p><p><br/></p></body></html>", None))
        self.titulo_confirmar_senha.setText(QCoreApplication.translate("cadastro", u"<html><head/><body><p>Senha</p></body></html>", None))
        self.imName.setPlaceholderText(QCoreApplication.translate("cadastro", u"Digite usuario", None))
        self.imPass.setPlaceholderText(QCoreApplication.translate("cadastro", u"Digite a senha", None))
        self.imPassC.setPlaceholderText(QCoreApplication.translate("cadastro", u"Confirme a senha", None))
        self.btnConfirma.setText(QCoreApplication.translate("cadastro", u"Confimar", None))
        self.btnLimpar.setText(QCoreApplication.translate("cadastro", u"Limpar", None))
        self.label_5.setText("")